### ISSUE TITLE
Cannot read property 'customization_info' of undefined

### ISSUE THREAD

**Issue by Pettask94** [ChatPlug/libfb-js#26]
In my local PoGo group we have 2 seperate raid messengers, therefore we also have 2 seperate discord channels. I got the first discord channel connected to its appropriate messenger, but when I try to connect the second discord/messenger, I get prompted with this error:

```
Cannot read property 'customization_info' of undefined
TypeError: Cannot read property 'customization_info' of undefined
    at FacebookApi.constructor.parseThread.thread [as parseThread] (C:\snapshot\miscord\node_modules\libfb\dist\FacebookApi.js:50:43)
    at FacebookApi.<anonymous> (C:\snapshot\miscord\node_modules\libfb\dist\FacebookApi.js:44:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\miscord\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

When I link the discord it says its successfull, it is only when I try to link the messenger I get this error.
After I get the error, the bot shuts down and I have to restart it.

**Comment by alufers** [comment]
https://github.com/ChatPlug/libfb-js/blob/master/src/FacebookApi.ts#L159 Line referenced in error

**Comment by SerekKiri** [comment]
This is libfb repository. 
Please report this issue here [miscord/issues](https://github.com/miscord/miscord/issues)
or join discord support server [discordapp.com/invite](https://discord.gg/RT6bvX).

Thanks 👍

**Comment by Bjornskjald** [comment]
@SerekKiri read the stack trace...
