### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by TryHardDood** [ChatPlug/libfb-js#66]
Code:
```
try {
    let client = new Client();
    client.login(req.body.email, req.body.password).then(() => {
        req.session.session = client.getSession();
        res.send('Logged in.');
    });
} catch (e) {
    res.send(e);
}
```

Error: 
```bash 
(node:3248) UnhandledPromiseRejectionWarning: Error: User must verify their account on www.facebook.com (405)
    at post.then.res (node_modules\libfb\dist\http\HttpApi.js:26:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Bjornskjald** [comment]
hey, did you try catching the error on the actual promise?

**Comment by TryHardDood** [comment]
`client.login(req.body.email, req.body.password)`  returns a Promise, or am I wrong?

**Comment by Bjornskjald** [comment]
yes, and promises have .catch methods which catch errors separately from try/catch

**Comment by TryHardDood** [comment]
> yes, and promises have .catch methods which catch errors separately from try/catch

Yep, you're right.
